import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getCurrentScheme } from "@/utils/themeScheme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const scheme = await getCurrentScheme();
  return (
    <html lang="en" className={scheme === "dark" ? "dark" : ""}>
      <body>{children}</body>
    </html>
  );
}
